# Decian Security Agent Configuration
# Organization: test123
dashboard:
  url: "https://localhost:3001"
  organization_id: "test123"

agent:
  version: "2.0.0"
  timeout: 300
  log_level: "INFO"

modules:
  - "MISCONFIGURATION_DISCOVERY"
  - "WEAK_PASSWORD_DETECTION"
  - "DATA_EXPOSURE_CHECK"
  - "PHISHING_EXPOSURE_INDICATORS"
  - "PATCH_UPDATE_STATUS"
  - "ELEVATED_PERMISSIONS_REPORT"
  - "EXCESSIVE_SHARING_RISKS"
  - "PASSWORD_POLICY_WEAKNESS"
  - "OPEN_SERVICE_PORT_ID"
  - "USER_BEHAVIOR_RISK_SIGNALS"

security:
  tls_version: "1.3"
  certificate_pinning: true
  encryption: true
  hmac_validation: true

settings:
  retry_attempts: 3
  retry_delay: "5s"
  heartbeat_interval: "60s"
