# Decian Agent Configuration Example
# Copy this file to .decian-agent.yaml and configure for your environment

agent:
  # Agent ID (set automatically during registration)
  id: ""

  # Hostname (defaults to system hostname)
  hostname: ""

  # Agent version
  version: "1.0.0"

  # Dry run mode - don't submit results to dashboard
  dry_run: false

dashboard:
  # Dashboard API endpoint URL (required)
  url: "https://your-dashboard.example.com"

  # Request timeout in seconds
  timeout: 30

auth:
  # Authentication token for dashboard API (required)
  token: "your-jwt-token-here"

assessment:
  # Default modules to run if none specified
  default_modules:
    - MISCONFIGURATION_DISCOVERY
    - WEAK_PASSWORD_DETECTION
    - DATA_EXPOSURE_CHECK
    - PHISHING_EXPOSURE_INDICATORS
    - PATCH_UPDATE_STATUS
    - ELEVATED_PERMISSIONS_REPORT
    - EXCESSIVE_SHARING_RISKS
    - PASSWORD_POLICY_WEAKNESS
    - OPEN_SERVICE_PORT_ID
    - USER_BEHAVIOR_RISK_SIGNALS

  # Module-specific configuration
  module_config:
    # Example: configure timeout for specific modules
    # MODULE_NAME: "timeout=300"

logging:
  # Enable verbose logging
  verbose: false

  # Log level (debug, info, warn, error)
  level: "info"

  # Log file path (optional, logs to stdout if not specified)
  file: ""